services:
  vaultwarden:
    image: vaultwarden/server:latest-alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.jshen.net"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 8000:80
#     networks:
#       - caddy
#
# networks:
#   caddy:
#     name: caddy_net
#     external: true
