services:
  orcaslicer:
    image: lscr.io/linuxserver/orcaslicer:latest
    container_name: orcaslicer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    # ports:
    #   - "3000:3000"
    #   - "3001:3001"
    volumes:
      - ./config:/config
    shm_size: "1gb"   # optional
    restart: unless-stopped
    networks:
      - caddy

networks:
  caddy:
    name: caddy_net
    external: true
