services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 10000:8096/tcp # web portal
      # - 10000:8920/tcp # 8920 is jellyfin https, 10000 is tailscale funnel allowed port
      # - 7359:7359/udp # client discovery, dont need it
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ./shows
        target: /shows
      - type: bind
        source: ./movies
        target: /movies
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: ./fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
